import React, { useState } from 'react';
import { Search, TrendingUp, TrendingDown, Minus, ExternalLink, Loader2 } from 'lucide-react';
import { analyzeMarketSentiment } from '../services/geminiService';
import { MarketInsight } from '../types';

const MarketPulse: React.FC = () => {
  const [query, setQuery] = useState('');
  const [insight, setInsight] = useState<MarketInsight | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleAnalyze = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsLoading(true);
    setInsight(null);
    
    try {
      const result = await analyzeMarketSentiment(query);
      setInsight(result);
    } finally {
      setIsLoading(false);
    }
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case 'Bullish': return 'text-green-600 bg-green-50 border-green-200';
      case 'Bearish': return 'text-red-600 bg-red-50 border-red-200';
      default: return 'text-slate-600 bg-slate-50 border-slate-200';
    }
  };

  const getSentimentIcon = (sentiment: string) => {
    switch (sentiment) {
      case 'Bullish': return <TrendingUp className="h-6 w-6" />;
      case 'Bearish': return <TrendingDown className="h-6 w-6" />;
      default: return <Minus className="h-6 w-6" />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-10">
          <h2 className="text-3xl font-serif font-bold text-primary">Market Pulse Analysis</h2>
          <p className="mt-2 text-slate-600">Enter a company, sector, or commodity to generate an AI-driven sentiment summary based on real-time news.</p>
        </div>

        <div className="bg-white rounded-xl shadow-lg p-6 mb-8">
          <form onSubmit={handleAnalyze} className="flex gap-2">
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="e.g., Apple Inc, Renewable Energy, Gold Prices"
              className="flex-1 rounded-lg border-slate-300 border p-3 focus:ring-2 focus:ring-accent focus:border-transparent outline-none"
            />
            <button
              type="submit"
              disabled={isLoading || !query.trim()}
              className="bg-primary text-white px-6 py-3 rounded-lg font-medium hover:bg-slate-800 transition-colors disabled:opacity-50 flex items-center gap-2"
            >
              {isLoading ? <Loader2 className="animate-spin h-5 w-5" /> : <Search className="h-5 w-5" />}
              Analyze
            </button>
          </form>
        </div>

        {insight && (
          <div className="bg-white rounded-xl shadow-lg overflow-hidden animate-fade-in-up">
            <div className="p-6 border-b border-slate-100 flex justify-between items-center">
              <h3 className="text-xl font-bold text-slate-900">{insight.symbol}</h3>
              <div className={`px-4 py-2 rounded-full border flex items-center gap-2 font-semibold ${getSentimentColor(insight.sentiment)}`}>
                {getSentimentIcon(insight.sentiment)}
                {insight.sentiment}
              </div>
            </div>
            
            <div className="p-6">
              <h4 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Executive Summary</h4>
              <p className="text-slate-800 leading-relaxed text-lg">
                {insight.summary}
              </p>
            </div>

            {insight.sources.length > 0 && (
              <div className="bg-slate-50 p-6 border-t border-slate-100">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">Sources & References</h4>
                <ul className="space-y-2">
                  {insight.sources.map((source, idx) => (
                    <li key={idx}>
                      <a 
                        href={source.uri} 
                        target="_blank" 
                        rel="noreferrer"
                        className="flex items-center gap-2 text-sm text-blue-600 hover:underline hover:text-blue-800 transition-colors"
                      >
                        <ExternalLink className="h-3 w-3" />
                        {source.title}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            
            <div className="bg-amber-50 p-4 border-t border-amber-100 text-amber-800 text-xs text-center">
              Disclaimer: This analysis is generated by AI using search data and should not be considered as financial advice.
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default MarketPulse;